#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: strapi
  newName: nginx
  newTag: 1.23

secretGenerator:
- envs:
  - secret.env
  name: strapi-env-secret

configMapGenerator:
- files:
  - strapi_configure.sh
  name: strapi-config
- files:
  - bootstrap.js
  name: strapi-bootstrap

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment.yml
- service.yml
